# constants.py

#CONSTANT VALUES FOR ALL MODELLING, THOSE PARAMETERS CAN BE CHANGE IF NEED IT
CONFIDENCE_INTERVAL = 0.95
MIN_TRAINING_SAMPLES = 20
TEST_YEAR = 2013
START_FORECASTING_YEAR = 2024
FORECASTING_LENGTH = 10
PROP_IN_CI_DESIRED = 0.8
FORECASTED_YEARS = 10
PROP_IN_CI_ALLOWED = 0.7
